project:
  type: website
  output-dir: docs

website: 
  #title: 'Chirag Sharma'
  favicon: favicon/icons8-darth-vader-512.png
  site-url: https://chirag1994.github.io/
  navbar: 
    left:
      - text: "Chirag Sharma's Blog"  
        href: index.qmd
      #- about.qmd  
    right: 
      - href: blog.qmd
        text: Blog
      - href: portfolio.qmd
        text: Portfolio
      - href: resume/chirag_sharma_resume.pdf
        text: Resume
      - icon: github
        href: https://github.com/Chirag1994
      - icon: linkedin
        href: https://www.linkedin.com/in/chiragsharma1994/
      - icon: envelope
        href: mailto:chirag.sharma0378@gmail.com

# format:
#   html:
#     theme:
#       - mystyles.scss
#     toc: true
# 
# editor: visual-studio-code

format:
  html:
    page-layout: full
    sidebar: false
    theme:
      - mystyle.scss
    # css: styles.css
    mainfont: Roboto
    #mainfont: Sharp Grotesk
    toc: true
    toc-expand: true