project:
  type: website
  output-dir: docs

website:
  title: "Chirag Sharma"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd   

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full

comments: 
  giscus: 
    repo:  Chirag1994/chiragsharma.github.io


