project:
  type: website
  output-dir: docs

website:
  title: "Chirag Sharma"
  favicon: favicon\icons8-darth-vader-512.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog      
      - href: portfolio.qmd
        text: Portfolio
      - href: resume/Resume.pdf
        text: Resume
      - icon: github # add icons that link to social media, etc.
        href: https://github.com/Chirag1994
      - icon: medium
        href: https://medium.com/@chirag.sharma0378
      - icon: linkedin
        href: https://www.linkedin.com/in/chiragsharma1994/
    page-footer: 
      background: light
      left: Copyright 2021, Chirag Sharma
      right: This website is built by [Quarto](https://quarto.org/)          

format:
  html:
    theme: 
      - mystyle.scss
    css: styles.css
    page-layout: full

comments: 
  giscus: 
    repo:  Chirag1994/chiragsharma.github.io