project:
  type: website
  output-dir: docs

website:
  title: "Chirag Sharma"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog      
      - href: portfolio.qmd
        text: Portfolio
      - href: resume/Chirag_Sharma_Resume.pdf
        text: Resume   

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    page-layout: full

comments: 
  giscus: 
    repo:  Chirag1994/chiragsharma.github.io

