<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chirag Sharma">
<meta name="dcterms.date" content="2024-01-05">
<meta name="description" content="In this post, we’ll tackle the second case study using MySQL from 8weeksqlchallenge.com. We’ll Explore the Pizza Runner case study with us, delving into the data to optimize operations and unveil customer insights using SQL analytics. Join the journey where ’80s Retro Styling and Pizza is the future drive the success of this innovative pizza delivery venture!">

<title>Case Study #5 - Data Mart.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon/icons8-darth-vader-512.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Chirag Sharma’s Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../portfolio.html" rel="" target="">
 <span class="menu-text">Portfolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume/chirag_sharma_resume.pdf" rel="" target="">
 <span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Chirag1994" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/chiragsharma1994/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:chirag.sharma0378@gmail.com" rel="" target=""><i class="bi bi-envelope" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Case Study #5 - Data Mart.</h1>
                  <div>
        <div class="description">
          In this post, we’ll tackle the second case study using MySQL from 8weeksqlchallenge.com. We’ll Explore the Pizza Runner case study with us, delving into the data to optimize operations and unveil customer insights using SQL analytics. Join the journey where ’80s Retro Styling and Pizza is the future drive the success of this innovative pizza delivery venture!
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">MySQL</div>
                <div class="quarto-category">SQL</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p><a href="https://chirag1994.github.io/">Chirag Sharma</a> </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 5, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#case-study-2---data-mart" id="toc-case-study-2---data-mart" class="nav-link active" data-scroll-target="#case-study-2---data-mart">Case Study #2 - Data Mart</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#available-data" id="toc-available-data" class="nav-link" data-scroll-target="#available-data">Available Data</a>
  <ul class="collapse">
  <li><a href="#column-dictionary" id="toc-column-dictionary" class="nav-link" data-scroll-target="#column-dictionary">Column Dictionary</a></li>
  <li><a href="#example-rows" id="toc-example-rows" class="nav-link" data-scroll-target="#example-rows">Example Rows</a></li>
  </ul></li>
  <li><a href="#interactive-sql-session" id="toc-interactive-sql-session" class="nav-link" data-scroll-target="#interactive-sql-session">Interactive SQL Session</a></li>
  <li><a href="#case-study-questions" id="toc-case-study-questions" class="nav-link" data-scroll-target="#case-study-questions">Case Study Questions</a>
  <ul class="collapse">
  <li><a href="#data-cleansing-steps" id="toc-data-cleansing-steps" class="nav-link" data-scroll-target="#data-cleansing-steps">1. Data Cleansing Steps</a></li>
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration">2. Data Exploration</a></li>
  <li><a href="#before-after-analysis" id="toc-before-after-analysis" class="nav-link" data-scroll-target="#before-after-analysis">3. Before &amp; After Analysis</a></li>
  <li><a href="#bonus-question" id="toc-bonus-question" class="nav-link" data-scroll-target="#bonus-question">4. Bonus Question</a></li>
  </ul></li>
  <li><a href="#lets-start-solving-them." id="toc-lets-start-solving-them." class="nav-link" data-scroll-target="#lets-start-solving-them.">Let’s start solving them.</a>
  <ul class="collapse">
  <li><a href="#data-cleansing-steps-1" id="toc-data-cleansing-steps-1" class="nav-link" data-scroll-target="#data-cleansing-steps-1">1. Data Cleansing Steps</a></li>
  </ul></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a>
  <ul class="collapse">
  <li><a href="#cleaning-clean_weekly_sales-table" id="toc-cleaning-clean_weekly_sales-table" class="nav-link" data-scroll-target="#cleaning-clean_weekly_sales-table">Cleaning clean_weekly_sales Table</a></li>
  </ul></li>
  <li><a href="#data-exploration-1" id="toc-data-exploration-1" class="nav-link" data-scroll-target="#data-exploration-1">2. Data Exploration</a>
  <ul class="collapse">
  <li><a href="#what-day-of-the-week-is-used-for-each-week_date-value" id="toc-what-day-of-the-week-is-used-for-each-week_date-value" class="nav-link" data-scroll-target="#what-day-of-the-week-is-used-for-each-week_date-value">1. What day of the week is used for each week_date value?</a></li>
  <li><a href="#what-range-of-week-numbers-are-missing-from-the-dataset" id="toc-what-range-of-week-numbers-are-missing-from-the-dataset" class="nav-link" data-scroll-target="#what-range-of-week-numbers-are-missing-from-the-dataset">2. What range of week numbers are missing from the dataset?</a></li>
  <li><a href="#how-many-total-transactions-were-there-for-each-year-in-the-dataset" id="toc-how-many-total-transactions-were-there-for-each-year-in-the-dataset" class="nav-link" data-scroll-target="#how-many-total-transactions-were-there-for-each-year-in-the-dataset">3. How many total transactions were there for each year in the dataset?</a></li>
  <li><a href="#what-is-the-total-sales-for-each-region-for-each-month" id="toc-what-is-the-total-sales-for-each-region-for-each-month" class="nav-link" data-scroll-target="#what-is-the-total-sales-for-each-region-for-each-month">4. What is the total sales for each region for each month?</a></li>
  <li><a href="#what-is-the-total-count-of-transactions-for-each-platform" id="toc-what-is-the-total-count-of-transactions-for-each-platform" class="nav-link" data-scroll-target="#what-is-the-total-count-of-transactions-for-each-platform">5. What is the total count of transactions for each platform?</a></li>
  <li><a href="#what-is-the-percentage-of-sales-for-retail-vs-shopify-for-each-month" id="toc-what-is-the-percentage-of-sales-for-retail-vs-shopify-for-each-month" class="nav-link" data-scroll-target="#what-is-the-percentage-of-sales-for-retail-vs-shopify-for-each-month">6. What is the percentage of sales for Retail vs Shopify for each month?</a></li>
  <li><a href="#what-is-the-percentage-of-sales-by-demographic-for-each-year-in-the-dataset" id="toc-what-is-the-percentage-of-sales-by-demographic-for-each-year-in-the-dataset" class="nav-link" data-scroll-target="#what-is-the-percentage-of-sales-by-demographic-for-each-year-in-the-dataset">7. What is the percentage of sales by demographic for each year in the dataset?</a></li>
  <li><a href="#which-age_band-and-demographic-values-contribute-the-most-to-retail-sales" id="toc-which-age_band-and-demographic-values-contribute-the-most-to-retail-sales" class="nav-link" data-scroll-target="#which-age_band-and-demographic-values-contribute-the-most-to-retail-sales">8. Which age_band and demographic values contribute the most to Retail sales?</a></li>
  <li><a href="#can-we-use-the-avg_transaction-column-to-find-the-average-transaction-size-for-each-year-for-retail-vs-shopify-if-not---how-would-you-calculate-it-instead" id="toc-can-we-use-the-avg_transaction-column-to-find-the-average-transaction-size-for-each-year-for-retail-vs-shopify-if-not---how-would-you-calculate-it-instead" class="nav-link" data-scroll-target="#can-we-use-the-avg_transaction-column-to-find-the-average-transaction-size-for-each-year-for-retail-vs-shopify-if-not---how-would-you-calculate-it-instead">9. Can we use the avg_transaction column to find the average transaction size for each year for Retail vs Shopify? If not - how would you calculate it instead?</a></li>
  <li><a href="#before-after-analysis-1" id="toc-before-after-analysis-1" class="nav-link" data-scroll-target="#before-after-analysis-1">3. Before &amp; After Analysis</a></li>
  <li><a href="#what-is-the-total-sales-for-the-4-weeks-before-and-after-2020-06-15-what-is-the-growth-or-reduction-rate-in-actual-values-and-percentage-of-sales" id="toc-what-is-the-total-sales-for-the-4-weeks-before-and-after-2020-06-15-what-is-the-growth-or-reduction-rate-in-actual-values-and-percentage-of-sales" class="nav-link" data-scroll-target="#what-is-the-total-sales-for-the-4-weeks-before-and-after-2020-06-15-what-is-the-growth-or-reduction-rate-in-actual-values-and-percentage-of-sales">1. What is the total sales for the 4 weeks before and after 2020-06-15? What is the growth or reduction rate in actual values and percentage of sales? */</a></li>
  <li><a href="#what-about-the-entire-12-weeks-before-and-after" id="toc-what-about-the-entire-12-weeks-before-and-after" class="nav-link" data-scroll-target="#what-about-the-entire-12-weeks-before-and-after">2. What about the entire 12 weeks before and after?</a></li>
  <li><a href="#how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-4-weeks-period" id="toc-how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-4-weeks-period" class="nav-link" data-scroll-target="#how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-4-weeks-period">3. How do the sale metrics for these 2 periods before and after compare with the previous years in 2018 and 2019 for 4 weeks period?</a></li>
  <li><a href="#how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-4-weeks-period-1" id="toc-how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-4-weeks-period-1" class="nav-link" data-scroll-target="#how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-4-weeks-period-1">3. How do the sale metrics for these 2 periods before and after compare with the previous years in 2018 and 2019 for 4 weeks period?</a></li>
  <li><a href="#part-3.2-how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-12-weeks-period" id="toc-part-3.2-how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-12-weeks-period" class="nav-link" data-scroll-target="#part-3.2-how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-12-weeks-period">Part 3.2: How do the sale metrics for these 2 periods before and after compare with the previous years in 2018 and 2019 for 12 weeks period?</a></li>
  <li><a href="#bonus-question-1" id="toc-bonus-question-1" class="nav-link" data-scroll-target="#bonus-question-1">4. Bonus Question</a></li>
  <li><a href="#which-areas-of-the-business-have-the-highest-negative-impact-in-sales-metrics-performance-in-2020-for-the-12-week-before-and-after-period" id="toc-which-areas-of-the-business-have-the-highest-negative-impact-in-sales-metrics-performance-in-2020-for-the-12-week-before-and-after-period" class="nav-link" data-scroll-target="#which-areas-of-the-business-have-the-highest-negative-impact-in-sales-metrics-performance-in-2020-for-the-12-week-before-and-after-period">Which areas of the business have the highest negative impact in sales metrics performance in 2020 for the 12 week before and after period?</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">




<section id="case-study-2---data-mart" class="level1">
<h1>Case Study #2 - Data Mart</h1>
<p><img src="./Images/Case_Study_5-Data_Mart.png" alt="Image1" width="800" height="800"></p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Data Mart is Danny’s latest venture and after running international operations for his online supermarket that specialises in fresh produce - Danny is asking for your support to analyse his sales performance.</p>
<p>In June 2020 - large scale supply changes were made at Data Mart. All Data Mart products now use sustainable packaging methods in every single step from the farm all the way to the customer.</p>
<p>Danny needs your help to quantify the impact of this change on the sales performance for Data Mart and it’s separate business areas.</p>
<p>The key business question he wants you to help him answer are the following:</p>
<ul>
<li><p>What was the quantifiable impact of the changes introduced in June 2020?</p></li>
<li><p>Which platform, region, segment and customer types were the most impacted by this change?</p></li>
<li><p>What can we do about future introduction of similar sustainability updates to the business to minimise impact on sales?</p></li>
</ul>
</section>
<section id="available-data" class="level2">
<h2 class="anchored" data-anchor-id="available-data">Available Data</h2>
<p>For this case study there is only a single table: <code>data_mart.weekly_sales</code></p>
<p>The <code>Entity Relationship Diagram</code> is shown below with the data types made clear, please note that there is only this one table - hence why it looks a little bit lonely!</p>
<p><img src="./Images/Case_Study_5-ER_Diagram.png" alt="Image1" width="800" height="800"></p>
<section id="column-dictionary" class="level3">
<h3 class="anchored" data-anchor-id="column-dictionary">Column Dictionary</h3>
<p>The columns are pretty self-explanatory based on the column names but here are some further details about the dataset:</p>
<ol type="1">
<li><p>Data Mart has international operations using a <code>multi-region</code> strategy</p></li>
<li><p>Data Mart has both, a retail and online <code>platform</code> in the form of a Shopify store front to serve their customers</p></li>
<li><p>Customer <code>segment</code> and <code>customer_type</code> data relates to personal age and demographics information that is shared with Data Mart.</p></li>
<li><p><code>transactions</code> is the count of unique purchases made through Data Mart and sales is the actual dollar amount of purchases</p></li>
</ol>
<p>Each record in the dataset is related to a specific aggregated slice of the underlying sales data rolled up into a week_date value which represents the start of the sales week.</p>
</section>
<section id="example-rows" class="level3">
<h3 class="anchored" data-anchor-id="example-rows">Example Rows</h3>
<p>10 random rows are shown in the table output below from <code>data_mart.weekly_sales</code>:</p>
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>week_date</th>
<th>region</th>
<th>platform</th>
<th>segment</th>
<th>customer_type</th>
<th>transactions</th>
<th>sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9/9/20</td>
<td>OCEANIA</td>
<td>Shopify</td>
<td>C3</td>
<td>New</td>
<td>610</td>
<td>110033.89</td>
</tr>
<tr class="even">
<td>29/7/20</td>
<td>AFRICA</td>
<td>Retail</td>
<td>C1</td>
<td>New</td>
<td>110692</td>
<td>3053771.19</td>
</tr>
<tr class="odd">
<td>22/7/20</td>
<td>EUROPE</td>
<td>Shopify</td>
<td>C4</td>
<td>Existing</td>
<td>24</td>
<td>8101.54</td>
</tr>
<tr class="even">
<td>13/5/20</td>
<td>AFRICA</td>
<td>Shopify</td>
<td>null</td>
<td>Guest</td>
<td>5287</td>
<td>1003301.37</td>
</tr>
<tr class="odd">
<td>24/7/19</td>
<td>ASIA</td>
<td>Retail</td>
<td>C1</td>
<td>New</td>
<td>127342</td>
<td>3151780.41</td>
</tr>
<tr class="even">
<td>10/7/19</td>
<td>CANADA</td>
<td>Shopify</td>
<td>F3</td>
<td>New</td>
<td>51</td>
<td>8844.93</td>
</tr>
<tr class="odd">
<td>26/6/19</td>
<td>OCEANIA</td>
<td>Retail</td>
<td>C3</td>
<td>New</td>
<td>152921</td>
<td>5551385.36</td>
</tr>
<tr class="even">
<td>29/5/19</td>
<td>SOUTH AMERICA</td>
<td>Shopify</td>
<td>null</td>
<td>New</td>
<td>53</td>
<td>10056.2</td>
</tr>
<tr class="odd">
<td>22/8/18</td>
<td>AFRICA</td>
<td>Retail</td>
<td>null</td>
<td>Existing</td>
<td>31721</td>
<td>1718863.58</td>
</tr>
<tr class="even">
<td>25/7/18</td>
<td>SOUTH AMERICA</td>
<td>Retail</td>
<td>null</td>
<td>New</td>
<td>2136</td>
<td>81757.91</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="interactive-sql-session" class="level2">
<h2 class="anchored" data-anchor-id="interactive-sql-session">Interactive SQL Session</h2>
<p>The Dataset for this case study can be accessed from <a href="https://www.db-fiddle.com/f/7VcQKQwsS3CTkGRFG7vu98/65">here</a>. I will be using MySQL to solve this case study. In order to solve yourself this case study, simply go to the above link and choose MySQL Dialect (version &gt; 8, if using MySQL version higher than 8 locally), copy &amp; paste the Database schema into MySQL.</p>
<p>Here is the snapshot of it.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">SCHEMA</span> data_mart;</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="kw">USE</span> data_mart;</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="kw">DROP</span> <span class="kw">TABLE</span> <span class="cf">IF</span> <span class="kw">EXISTS</span> data_mart.weekly_sales;</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> data_mart.weekly_sales (</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  `week_date` <span class="dt">VARCHAR</span>(<span class="dv">7</span>),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  `region` <span class="dt">VARCHAR</span>(<span class="dv">13</span>),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  `platform` <span class="dt">VARCHAR</span>(<span class="dv">7</span>),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  `segment` <span class="dt">VARCHAR</span>(<span class="dv">4</span>),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  `customer_type` <span class="dt">VARCHAR</span>(<span class="dv">8</span>),</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  `transactions` <span class="dt">INTEGER</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  `sales` <span class="dt">INTEGER</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>);</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="kw">INSERT</span> <span class="kw">INTO</span> data_mart.weekly_sales</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  (`week_date`, `region`, `platform`, `segment`, `customer_type`, `transactions`, `sales`)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="kw">VALUES</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'ASIA'</span>, <span class="st">'Retail'</span>, <span class="st">'C3'</span>, <span class="st">'New'</span>, <span class="st">'120631'</span>, <span class="st">'3656163'</span>),</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'ASIA'</span>, <span class="st">'Retail'</span>, <span class="st">'F1'</span>, <span class="st">'New'</span>, <span class="st">'31574'</span>, <span class="st">'996575'</span>),</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'USA'</span>, <span class="st">'Retail'</span>, <span class="st">'null'</span>, <span class="st">'Guest'</span>, <span class="st">'529151'</span>, <span class="st">'16509610'</span>),</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'EUROPE'</span>, <span class="st">'Retail'</span>, <span class="st">'C1'</span>, <span class="st">'New'</span>, <span class="st">'4517'</span>, <span class="st">'141942'</span>),</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'AFRICA'</span>, <span class="st">'Retail'</span>, <span class="st">'C2'</span>, <span class="st">'New'</span>, <span class="st">'58046'</span>, <span class="st">'1758388'</span>),</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'CANADA'</span>, <span class="st">'Shopify'</span>, <span class="st">'F2'</span>, <span class="st">'Existing'</span>, <span class="st">'1336'</span>, <span class="st">'243878'</span>),</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'AFRICA'</span>, <span class="st">'Shopify'</span>, <span class="st">'F3'</span>, <span class="st">'Existing'</span>, <span class="st">'2514'</span>, <span class="st">'519502'</span>),</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'ASIA'</span>, <span class="st">'Shopify'</span>, <span class="st">'F1'</span>, <span class="st">'Existing'</span>, <span class="st">'2158'</span>, <span class="st">'371417'</span>),</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'AFRICA'</span>, <span class="st">'Shopify'</span>, <span class="st">'F2'</span>, <span class="st">'New'</span>, <span class="st">'318'</span>, <span class="st">'49557'</span>),</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'AFRICA'</span>, <span class="st">'Retail'</span>, <span class="st">'C3'</span>, <span class="st">'New'</span>, <span class="st">'111032'</span>, <span class="st">'3888162'</span>),</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'USA'</span>, <span class="st">'Shopify'</span>, <span class="st">'F1'</span>, <span class="st">'Existing'</span>, <span class="st">'1398'</span>, <span class="st">'260773'</span>),</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'OCEANIA'</span>, <span class="st">'Shopify'</span>, <span class="st">'C2'</span>, <span class="st">'Existing'</span>, <span class="st">'4661'</span>, <span class="st">'882690'</span>),</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'SOUTH AMERICA'</span>, <span class="st">'Retail'</span>, <span class="st">'C2'</span>, <span class="st">'Existing'</span>, <span class="st">'1029'</span>, <span class="st">'38762'</span>),</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'SOUTH AMERICA'</span>, <span class="st">'Shopify'</span>, <span class="st">'C4'</span>, <span class="st">'New'</span>, <span class="st">'6'</span>, <span class="st">'917'</span>),</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'EUROPE'</span>, <span class="st">'Shopify'</span>, <span class="st">'F3'</span>, <span class="st">'Existing'</span>, <span class="st">'115'</span>, <span class="st">'35215'</span>),</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'OCEANIA'</span>, <span class="st">'Retail'</span>, <span class="st">'F3'</span>, <span class="st">'Existing'</span>, <span class="st">'551905'</span>, <span class="st">'30371770'</span>),</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'ASIA'</span>, <span class="st">'Shopify'</span>, <span class="st">'C3'</span>, <span class="st">'Existing'</span>, <span class="st">'1969'</span>, <span class="st">'374327'</span>),</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'AFRICA'</span>, <span class="st">'Retail'</span>, <span class="st">'F1'</span>, <span class="st">'Existing'</span>, <span class="st">'97604'</span>, <span class="st">'5185233'</span>),</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'OCEANIA'</span>, <span class="st">'Retail'</span>, <span class="st">'C2'</span>, <span class="st">'New'</span>, <span class="st">'111219'</span>, <span class="st">'2980673'</span>),</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'USA'</span>, <span class="st">'Retail'</span>, <span class="st">'F1'</span>, <span class="st">'New'</span>, <span class="st">'11820'</span>, <span class="st">'463738'</span>),</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'SOUTH AMERICA'</span>, <span class="st">'Retail'</span>, <span class="st">'F3'</span>, <span class="st">'Existing'</span>, <span class="st">'1363'</span>, <span class="st">'65730'</span>),</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'AFRICA'</span>, <span class="st">'Retail'</span>, <span class="st">'C3'</span>, <span class="st">'Existing'</span>, <span class="st">'284971'</span>, <span class="st">'14430196'</span>),</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'ASIA'</span>, <span class="st">'Retail'</span>, <span class="st">'F2'</span>, <span class="st">'New'</span>, <span class="st">'70496'</span>, <span class="st">'2176980'</span>),</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'AFRICA'</span>, <span class="st">'Shopify'</span>, <span class="st">'F1'</span>, <span class="st">'Existing'</span>, <span class="st">'2678'</span>, <span class="st">'478756'</span>),</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'USA'</span>, <span class="st">'Shopify'</span>, <span class="st">'C4'</span>, <span class="st">'New'</span>, <span class="st">'22'</span>, <span class="st">'3319'</span>),</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'CANADA'</span>, <span class="st">'Retail'</span>, <span class="st">'F3'</span>, <span class="st">'Existing'</span>, <span class="st">'94274'</span>, <span class="st">'5306746'</span>),</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'ASIA'</span>, <span class="st">'Retail'</span>, <span class="st">'F1'</span>, <span class="st">'Existing'</span>, <span class="st">'94287'</span>, <span class="st">'4511841'</span>),</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'EUROPE'</span>, <span class="st">'Retail'</span>, <span class="st">'null'</span>, <span class="st">'New'</span>, <span class="st">'3064'</span>, <span class="st">'134249'</span>),</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'EUROPE'</span>, <span class="st">'Shopify'</span>, <span class="st">'F1'</span>, <span class="st">'New'</span>, <span class="st">'7'</span>, <span class="st">'1579'</span>),</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'SOUTH AMERICA'</span>, <span class="st">'Retail'</span>, <span class="st">'C4'</span>, <span class="st">'New'</span>, <span class="st">'329'</span>, <span class="st">'11451'</span>),</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'SOUTH AMERICA'</span>, <span class="st">'Retail'</span>, <span class="st">'F1'</span>, <span class="st">'Existing'</span>, <span class="st">'854'</span>, <span class="st">'31589'</span>),</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>  (<span class="st">'31/8/20'</span>, <span class="st">'EUROPE'</span>, <span class="st">'Shopify'</span>, <span class="st">'C2'</span>, <span class="st">'Existing'</span>, <span class="st">'180'</span>, <span class="st">'53567'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="case-study-questions" class="level2">
<h2 class="anchored" data-anchor-id="case-study-questions">Case Study Questions</h2>
<p>The following case study questions require some data cleaning steps before we start to unpack Danny’s key business questions in more depth.</p>
<section id="data-cleansing-steps" class="level3">
<h3 class="anchored" data-anchor-id="data-cleansing-steps">1. Data Cleansing Steps</h3>
<p>In a single query, perform the following operations and generate a new table in the <code>data_mart</code> schema named <code>clean_weekly_sales</code>:</p>
<ul>
<li><p>Convert the <code>week_date</code> to a DATE format</p></li>
<li><p>Add a <code>week_number</code> as the second column for each <code>week_date</code> value, for example any value from the 1st of January to 7th of January will be 1, 8th to 14th will be 2 etc.</p></li>
<li><p>Add a <code>month_number</code> with the calendar month for each <code>week_date</code> value as the 3rd column.</p></li>
<li><p>Add a <code>calendar_year</code> column as the 4th column containing either 2018, 2019 or 2020 values.</p></li>
<li><p>Add a new column called <code>age_band</code> after the original segment column using the following mapping on the number inside the segment value.</p></li>
</ul>
<table class="table">
<thead>
<tr class="header">
<th>segment</th>
<th>age_band</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Young Adults</td>
</tr>
<tr class="even">
<td>2</td>
<td>Middle Aged</td>
</tr>
<tr class="odd">
<td>3 or 4</td>
<td>Retirees</td>
</tr>
</tbody>
</table>
<ul>
<li>Add a new <code>demographic</code> column using the following mapping for the first letter in the <code>segment</code> values:</li>
</ul>
<table class="table">
<thead>
<tr class="header">
<th>segment</th>
<th>demographic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C</td>
<td>Couples</td>
</tr>
<tr class="even">
<td>F</td>
<td>Families</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Ensure all <code>null</code> string values with an <code>"unknown"</code> string value in the original <code>segment</code> column as well as the new <code>age_band</code> and <code>demographic</code> columns</p></li>
<li><p>Generate a new <code>avg_transaction</code> column as the <code>sales</code> value divided by <code>transactions</code> rounded to 2 decimal places for each record</p></li>
</ul>
</section>
<section id="data-exploration" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration">2. Data Exploration</h3>
<ol type="1">
<li><p>What day of the week is used for each week_date value?</p></li>
<li><p>What range of week numbers are missing from the dataset?</p></li>
<li><p>How many total transactions were there for each year in the dataset?</p></li>
<li><p>What is the total sales for each region for each month?</p></li>
<li><p>What is the total count of transactions for each platform</p></li>
<li><p>What is the percentage of sales for Retail vs Shopify for each month?</p></li>
<li><p>What is the percentage of sales by demographic for each year in the dataset?</p></li>
<li><p>Which age_band and demographic values contribute the most to Retail sales?</p></li>
<li><p>Can we use the avg_transaction column to find the average transaction size for each year for Retail vs Shopify? If not - how would you calculate it instead?</p></li>
</ol>
</section>
<section id="before-after-analysis" class="level3">
<h3 class="anchored" data-anchor-id="before-after-analysis">3. Before &amp; After Analysis</h3>
<p>This technique is usually used when we inspect an important event and want to inspect the impact before and after a certain point in time.</p>
<p>Taking the <code>week_date</code> value of <code>2020-06-15</code> as the baseline week where the Data Mart sustainable packaging changes came into effect.</p>
<p>We would include all <code>week_date</code> values for <code>2020-06-15</code> as the start of the period <strong>after</strong> the change and the previous <code>week_date</code> values would be <strong>before</strong></p>
<p>Using this analysis approach - answer the following questions:</p>
<ol type="1">
<li><p>What is the total sales for the 4 weeks before and after 2020-06-15? What is the growth or reduction rate in actual values and percentage of sales?</p></li>
<li><p>What about the entire 12 weeks before and after?</p></li>
<li><p>How do the sale metrics for these 2 periods before and after compare with the previous years in 2018 and 2019?</p></li>
</ol>
</section>
<section id="bonus-question" class="level3">
<h3 class="anchored" data-anchor-id="bonus-question">4. Bonus Question</h3>
<p>Which areas of the business have the highest negative impact in sales metrics performance in 2020 for the 12 week before and after period?</p>
<ul>
<li><code>region</code></li>
<li><code>platform</code></li>
<li><code>age_band</code></li>
<li><code>demographic</code></li>
<li><code>customer_type</code></li>
</ul>
<p>Do you have any further recommendations for Danny’s team at Data Mart or any interesting insights based off this analysis?</p>
</section>
</section>
<section id="lets-start-solving-them." class="level2">
<h2 class="anchored" data-anchor-id="lets-start-solving-them.">Let’s start solving them.</h2>
<section id="data-cleansing-steps-1" class="level3">
<h3 class="anchored" data-anchor-id="data-cleansing-steps-1">1. Data Cleansing Steps</h3>
<p>In a single query, perform the following operations and generate a new table in the <code>data_mart</code> schema named <code>clean_weekly_sales</code>:</p>
<ul>
<li><p>Convert the <code>week_date</code> to a DATE format</p></li>
<li><p>Add a <code>week_number</code> as the second column for each <code>week_date</code> value, for example any value from the 1st of January to 7th of January will be 1, 8th to 14th will be 2 etc.</p></li>
<li><p>Add a <code>month_number</code> with the calendar month for each <code>week_date</code> value as the 3rd column.</p></li>
<li><p>Add a <code>calendar_year</code> column as the 4th column containing either 2018, 2019 or 2020 values.</p></li>
<li><p>Add a new column called <code>age_band</code> after the original segment column using the following mapping on the number inside the segment value.</p></li>
</ul>
<table class="table">
<thead>
<tr class="header">
<th>segment</th>
<th>age_band</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Young Adults</td>
</tr>
<tr class="even">
<td>2</td>
<td>Middle Aged</td>
</tr>
<tr class="odd">
<td>3 or 4</td>
<td>Retirees</td>
</tr>
</tbody>
</table>
<ul>
<li>Add a new <code>demographic</code> column using the following mapping for the first letter in the <code>segment</code> values:</li>
</ul>
<table class="table">
<thead>
<tr class="header">
<th>segment</th>
<th>demographic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C</td>
<td>Couples</td>
</tr>
<tr class="even">
<td>F</td>
<td>Families</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Ensure all <code>null</code> string values with an <code>"unknown"</code> string value in the original <code>segment</code> column as well as the new <code>age_band</code> and <code>demographic</code> columns</p></li>
<li><p>Generate a new <code>avg_transaction</code> column as the <code>sales</code> value divided by <code>transactions</code> rounded to 2 decimal places for each record</p></li>
</ul>
</section>
</section>
<section id="data-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning">Data Cleaning</h2>
<section id="cleaning-clean_weekly_sales-table" class="level3">
<h3 class="anchored" data-anchor-id="cleaning-clean_weekly_sales-table">Cleaning clean_weekly_sales Table</h3>
<div class="sourceCode" id="cb2"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">DROP</span> <span class="kw">TABLE</span> <span class="cf">IF</span> <span class="kw">EXISTS</span> data_mart.clean_weekly_sales</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> data_mart.clean_weekly_sales <span class="kw">AS</span> (</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  STR_TO_DATE(week_date, <span class="st">'%d/%m/%y'</span>) <span class="kw">AS</span> week_date,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  WEEK(STR_TO_DATE(week_date, <span class="st">'%d/%m/%y'</span>)) <span class="kw">AS</span> week_number,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">MONTH</span>(STR_TO_DATE(week_date, <span class="st">'%d/%m/%y'</span>)) <span class="kw">AS</span> month_number,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">YEAR</span>(STR_TO_DATE(week_date, <span class="st">'%d/%m/%y'</span>)) <span class="kw">AS</span> calendar_year,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  region,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  platform,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">CASE</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">WHEN</span> <span class="kw">RIGHT</span>(<span class="kw">segment</span>, <span class="dv">1</span>) <span class="op">=</span> <span class="st">'1'</span> <span class="cf">THEN</span> <span class="st">'Young Adults'</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">WHEN</span> <span class="kw">RIGHT</span>(<span class="kw">segment</span>, <span class="dv">1</span>) <span class="op">=</span> <span class="st">'2'</span> <span class="cf">THEN</span> <span class="st">'Middle Aged'</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">WHEN</span> <span class="kw">RIGHT</span>(<span class="kw">segment</span>, <span class="dv">1</span>) <span class="kw">IN</span> (<span class="st">'3'</span>, <span class="st">'4'</span>) <span class="cf">THEN</span> <span class="st">'Retirees'</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">ELSE</span> <span class="st">'unknown'</span> <span class="cf">END</span> <span class="kw">AS</span> age_band,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="cf">CASE</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">WHEN</span> <span class="kw">LEFT</span>(<span class="kw">segment</span>, <span class="dv">1</span>) <span class="op">=</span> <span class="st">'C'</span> <span class="cf">THEN</span> <span class="st">'Couples'</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">WHEN</span> <span class="kw">LEFT</span>(<span class="kw">segment</span>, <span class="dv">1</span>) <span class="op">=</span> <span class="st">'F'</span> <span class="cf">THEN</span> <span class="st">'Families'</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">ELSE</span> <span class="st">'unknown'</span> <span class="cf">END</span> <span class="kw">AS</span> demographic,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">COALESCE</span>(<span class="fu">NULLIF</span>(<span class="kw">segment</span>, <span class="st">''</span>), <span class="st">'unknown'</span>) <span class="kw">AS</span> <span class="kw">segment</span>,</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  transactions,</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ROUND</span>((sales <span class="op">/</span> transactions), <span class="dv">2</span>) <span class="kw">AS</span> avg_transaction,</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  sales</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> data_mart.weekly_sales</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>);</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="kw">UPDATE</span> data_mart.clean_weekly_sales</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="kw">SET</span> age_band <span class="op">=</span> <span class="st">'unknown'</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> age_band <span class="kw">IS</span> <span class="kw">NULL</span>;</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="kw">UPDATE</span> data_mart.clean_weekly_sales</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="kw">SET</span> demographic <span class="op">=</span> <span class="st">'unknown'</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> demographic <span class="kw">IS</span> <span class="kw">NULL</span>;</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="kw">UPDATE</span> data_mart.clean_weekly_sales</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a><span class="kw">SET</span> <span class="kw">segment</span> <span class="op">=</span> <span class="st">'unknown'</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> <span class="kw">segment</span> <span class="kw">IS</span> <span class="kw">NULL</span>;</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span> <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">15</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<p>The first 15 records are shown as follows:</p>
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>week_date</th>
<th>week_number</th>
<th>month_number</th>
<th>calendar_year</th>
<th>region</th>
<th>platform</th>
<th>age_band</th>
<th>demographic_segment</th>
<th>transactions</th>
<th>avg_transaction</th>
<th>sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>ASIA</td>
<td>Retail</td>
<td>Retirees</td>
<td>Couples</td>
<td>120631</td>
<td>30.31</td>
<td>3656163</td>
</tr>
<tr class="even">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>ASIA</td>
<td>Retail</td>
<td>Young Adults</td>
<td>Families</td>
<td>31574</td>
<td>31.56</td>
<td>996575</td>
</tr>
<tr class="odd">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>USA</td>
<td>Retail</td>
<td>unknown</td>
<td>unknown</td>
<td>null</td>
<td>529151</td>
<td>31.20</td>
</tr>
<tr class="even">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>EUROPE</td>
<td>Retail</td>
<td>Young Adults</td>
<td>Couples</td>
<td>4517</td>
<td>31.42</td>
<td>141942</td>
</tr>
<tr class="odd">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>AFRICA</td>
<td>Retail</td>
<td>Middle Aged</td>
<td>Couples</td>
<td>58046</td>
<td>30.29</td>
<td>1758388</td>
</tr>
<tr class="even">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>CANADA</td>
<td>Shopify</td>
<td>Middle Aged</td>
<td>Families</td>
<td>1336</td>
<td>182.54</td>
<td>243878</td>
</tr>
<tr class="odd">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>AFRICA</td>
<td>Shopify</td>
<td>Retirees</td>
<td>Families</td>
<td>2514</td>
<td>206.64</td>
<td>519502</td>
</tr>
<tr class="even">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>ASIA</td>
<td>Shopify</td>
<td>Young Adults</td>
<td>Families</td>
<td>2158</td>
<td>172.11</td>
<td>371417</td>
</tr>
<tr class="odd">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>AFRICA</td>
<td>Shopify</td>
<td>Middle Aged</td>
<td>Families</td>
<td>318</td>
<td>155.84</td>
<td>49557</td>
</tr>
<tr class="even">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>AFRICA</td>
<td>Retail</td>
<td>Retirees</td>
<td>Couples</td>
<td>111032</td>
<td>35.02</td>
<td>3888162</td>
</tr>
<tr class="odd">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>USA</td>
<td>Shopify</td>
<td>Young Adults</td>
<td>Families</td>
<td>1398</td>
<td>186.53</td>
<td>260773</td>
</tr>
<tr class="even">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>OCEANIA</td>
<td>Shopify</td>
<td>Middle Aged</td>
<td>Couples</td>
<td>4661</td>
<td>189.38</td>
<td>882690</td>
</tr>
<tr class="odd">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>SOUTH AMERICA</td>
<td>Retail</td>
<td>Middle Aged</td>
<td>Couples</td>
<td>1029</td>
<td>37.67</td>
<td>38762</td>
</tr>
<tr class="even">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>SOUTH AMERICA</td>
<td>Shopify</td>
<td>Retirees</td>
<td>Couples</td>
<td>6</td>
<td>152.83</td>
<td>917</td>
</tr>
<tr class="odd">
<td>2020-08-31</td>
<td>35</td>
<td>8</td>
<td>2020</td>
<td>EUROPE</td>
<td>Shopify</td>
<td>Retirees</td>
<td>Families</td>
<td>115</td>
<td>306.22</td>
<td>35215</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="data-exploration-1" class="level2">
<h2 class="anchored" data-anchor-id="data-exploration-1">2. Data Exploration</h2>
<section id="what-day-of-the-week-is-used-for-each-week_date-value" class="level3">
<h3 class="anchored" data-anchor-id="what-day-of-the-week-is-used-for-each-week_date-value">1. What day of the week is used for each week_date value?</h3>
<div class="sourceCode" id="cb3"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">DISTINCT</span> DAYNAME(week_date) <span class="kw">AS</span> Day_Name</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> clean_weekly_sales;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<thead>
<tr class="header">
<th>Day_name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Monday</td>
</tr>
</tbody>
</table>
<section id="day-of-the-week-analysis-for-weekly-sales-data" class="level4">
<h4 class="anchored" data-anchor-id="day-of-the-week-analysis-for-weekly-sales-data">Day of the Week Analysis for Weekly Sales Data</h4>
<ol type="1">
<li><p><strong>Insight</strong>:</p>
<ul>
<li>The day of the week associated with each week_date value in the weekly_sales dataset is consistently Monday.</li>
</ul></li>
</ol>
</section>
</section>
<section id="what-range-of-week-numbers-are-missing-from-the-dataset" class="level3">
<h3 class="anchored" data-anchor-id="what-range-of-week-numbers-are-missing-from-the-dataset">2. What range of week numbers are missing from the dataset?</h3>
<div class="sourceCode" id="cb4"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> RECURSIVE NumbersSeries <span class="kw">AS</span> (</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="dv">1</span> <span class="kw">AS</span> week_number</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> <span class="kw">ALL</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> week_number <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> NumbersSeries</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">WHERE</span> week_number <span class="op">&lt;</span> <span class="dv">52</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> NumbersSeries.week_number</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> NumbersSeries</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> <span class="kw">NOT</span> <span class="kw">EXISTS</span> (</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="dv">1</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="kw">WHERE</span> week_number <span class="op">=</span> NumbersSeries.week_number</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<thead>
<tr class="header">
<th>week_number</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
</tr>
<tr class="even">
<td>2</td>
</tr>
<tr class="odd">
<td>3</td>
</tr>
<tr class="even">
<td>4</td>
</tr>
<tr class="odd">
<td>5</td>
</tr>
<tr class="even">
<td>6</td>
</tr>
<tr class="odd">
<td>7</td>
</tr>
<tr class="even">
<td>8</td>
</tr>
<tr class="odd">
<td>9</td>
</tr>
<tr class="even">
<td>10</td>
</tr>
<tr class="odd">
<td>11</td>
</tr>
<tr class="even">
<td>36</td>
</tr>
<tr class="odd">
<td>37</td>
</tr>
<tr class="even">
<td>38</td>
</tr>
<tr class="odd">
<td>39</td>
</tr>
<tr class="even">
<td>40</td>
</tr>
<tr class="odd">
<td>41</td>
</tr>
<tr class="even">
<td>42</td>
</tr>
<tr class="odd">
<td>43</td>
</tr>
<tr class="even">
<td>44</td>
</tr>
<tr class="odd">
<td>45</td>
</tr>
<tr class="even">
<td>46</td>
</tr>
<tr class="odd">
<td>47</td>
</tr>
<tr class="even">
<td>48</td>
</tr>
<tr class="odd">
<td>49</td>
</tr>
<tr class="even">
<td>50</td>
</tr>
<tr class="odd">
<td>51</td>
</tr>
<tr class="even">
<td>52</td>
</tr>
</tbody>
</table>
<section id="missing-week-numbers-in-the-dataset" class="level4">
<h4 class="anchored" data-anchor-id="missing-week-numbers-in-the-dataset">Missing Week Numbers in the Dataset</h4>
<ol type="1">
<li><p><strong>Insight</strong>:</p>
<ul>
<li>Several week numbers are missing from the dataset, ranging from week 1 to week 11 and week 36 to week 52.</li>
</ul></li>
</ol>
</section>
</section>
<section id="how-many-total-transactions-were-there-for-each-year-in-the-dataset" class="level3">
<h3 class="anchored" data-anchor-id="how-many-total-transactions-were-there-for-each-year-in-the-dataset">3. How many total transactions were there for each year in the dataset?</h3>
<div class="sourceCode" id="cb5"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> calendar_year,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(transactions) <span class="kw">as</span> total_transactions</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> calendar_year</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> calendar_year;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<thead>
<tr class="header">
<th>calendar_year</th>
<th>total_transactions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2018</td>
<td>346,406,460</td>
</tr>
<tr class="even">
<td>2019</td>
<td>365,639,285</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>375,813,651</td>
</tr>
</tbody>
</table>
<section id="total-transactions-by-year" class="level4">
<h4 class="anchored" data-anchor-id="total-transactions-by-year">Total Transactions by Year</h4>
<ol type="1">
<li><p><strong>Insight</strong>:</p>
<ul>
<li>The total number of transactions has shown a consistent upward trend over the years, with 2018 starting at a lower value compared to subsequent years.</li>
</ul></li>
</ol>
</section>
</section>
<section id="what-is-the-total-sales-for-each-region-for-each-month" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-total-sales-for-each-region-for-each-month">4. What is the total sales for each region for each month?</h3>
<div class="sourceCode" id="cb6"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> region, month_number,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(sales) <span class="kw">as</span> total_sales</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> region, month_number</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> region, month_number;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<thead>
<tr class="header">
<th>region</th>
<th>month_number</th>
<th>total_sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AFRICA</td>
<td>3</td>
<td>567,767,480</td>
</tr>
<tr class="even">
<td>AFRICA</td>
<td>4</td>
<td>1,911,783,504</td>
</tr>
<tr class="odd">
<td>AFRICA</td>
<td>5</td>
<td>1,647,244,738</td>
</tr>
<tr class="even">
<td>AFRICA</td>
<td>6</td>
<td>1,767,559,760</td>
</tr>
<tr class="odd">
<td>AFRICA</td>
<td>7</td>
<td>1,960,219,710</td>
</tr>
<tr class="even">
<td>AFRICA</td>
<td>8</td>
<td>1,809,596,890</td>
</tr>
<tr class="odd">
<td>AFRICA</td>
<td>9</td>
<td>276,320,987</td>
</tr>
<tr class="even">
<td>ASIA</td>
<td>3</td>
<td>529,770,793</td>
</tr>
<tr class="odd">
<td>ASIA</td>
<td>4</td>
<td>1,804,628,707</td>
</tr>
<tr class="even">
<td>ASIA</td>
<td>5</td>
<td>1,526,285,399</td>
</tr>
<tr class="odd">
<td>ASIA</td>
<td>6</td>
<td>1,619,482,889</td>
</tr>
<tr class="even">
<td>ASIA</td>
<td>7</td>
<td>1,768,844,756</td>
</tr>
<tr class="odd">
<td>ASIA</td>
<td>8</td>
<td>1,663,320,609</td>
</tr>
<tr class="even">
<td>ASIA</td>
<td>9</td>
<td>252,836,807</td>
</tr>
<tr class="odd">
<td>CANADA</td>
<td>3</td>
<td>144,634,329</td>
</tr>
<tr class="even">
<td>CANADA</td>
<td>4</td>
<td>484,552,594</td>
</tr>
<tr class="odd">
<td>CANADA</td>
<td>5</td>
<td>412,378,365</td>
</tr>
<tr class="even">
<td>CANADA</td>
<td>6</td>
<td>443,846,698</td>
</tr>
<tr class="odd">
<td>CANADA</td>
<td>7</td>
<td>477,134,947</td>
</tr>
<tr class="even">
<td>CANADA</td>
<td>8</td>
<td>447,073,019</td>
</tr>
<tr class="odd">
<td>CANADA</td>
<td>9</td>
<td>69,067,959</td>
</tr>
<tr class="even">
<td>EUROPE</td>
<td>3</td>
<td>35,337,093</td>
</tr>
<tr class="odd">
<td>EUROPE</td>
<td>4</td>
<td>127,334,255</td>
</tr>
<tr class="even">
<td>EUROPE</td>
<td>5</td>
<td>109,338,389</td>
</tr>
<tr class="odd">
<td>EUROPE</td>
<td>6</td>
<td>122,813,826</td>
</tr>
<tr class="even">
<td>EUROPE</td>
<td>7</td>
<td>136,757,466</td>
</tr>
<tr class="odd">
<td>EUROPE</td>
<td>8</td>
<td>122,102,995</td>
</tr>
<tr class="even">
<td>EUROPE</td>
<td>9</td>
<td>18,877,433</td>
</tr>
<tr class="odd">
<td>OCEANIA</td>
<td>3</td>
<td>783,282,888</td>
</tr>
<tr class="even">
<td>OCEANIA</td>
<td>4</td>
<td>2,599,767,620</td>
</tr>
<tr class="odd">
<td>OCEANIA</td>
<td>5</td>
<td>2,215,657,304</td>
</tr>
<tr class="even">
<td>OCEANIA</td>
<td>6</td>
<td>2,371,884,744</td>
</tr>
<tr class="odd">
<td>OCEANIA</td>
<td>7</td>
<td>2,563,459,400</td>
</tr>
<tr class="even">
<td>OCEANIA</td>
<td>8</td>
<td>2,432,313,652</td>
</tr>
<tr class="odd">
<td>OCEANIA</td>
<td>9</td>
<td>372,465,518</td>
</tr>
<tr class="even">
<td>SOUTH AMERICA</td>
<td>3</td>
<td>71,023,109</td>
</tr>
<tr class="odd">
<td>SOUTH AMERICA</td>
<td>4</td>
<td>238,451,531</td>
</tr>
<tr class="even">
<td>SOUTH AMERICA</td>
<td>5</td>
<td>201,391,809</td>
</tr>
<tr class="odd">
<td>SOUTH AMERICA</td>
<td>6</td>
<td>218,247,455</td>
</tr>
<tr class="even">
<td>SOUTH AMERICA</td>
<td>7</td>
<td>235,582,776</td>
</tr>
<tr class="odd">
<td>SOUTH AMERICA</td>
<td>8</td>
<td>221,166,052</td>
</tr>
<tr class="even">
<td>SOUTH AMERICA</td>
<td>9</td>
<td>34,175,583</td>
</tr>
<tr class="odd">
<td>USA</td>
<td>3</td>
<td>225,353,043</td>
</tr>
<tr class="even">
<td>USA</td>
<td>4</td>
<td>759,786,323</td>
</tr>
<tr class="odd">
<td>USA</td>
<td>5</td>
<td>655,967,121</td>
</tr>
<tr class="even">
<td>USA</td>
<td>6</td>
<td>703,878,990</td>
</tr>
<tr class="odd">
<td>USA</td>
<td>7</td>
<td>760,331,754</td>
</tr>
<tr class="even">
<td>USA</td>
<td>8</td>
<td>712,002,790</td>
</tr>
<tr class="odd">
<td>USA</td>
<td>9</td>
<td>110,532,368</td>
</tr>
</tbody>
</table>
<section id="total-sales-by-region-and-month" class="level4">
<h4 class="anchored" data-anchor-id="total-sales-by-region-and-month">Total Sales by Region and Month</h4>
<ol type="1">
<li><p><strong>Insight</strong>:</p>
<ul>
<li>Sales performance varies across regions and months, with some regions consistently outperforming others.</li>
</ul></li>
<li><p><strong>Overview</strong>:</p>
<ul>
<li>Africa: Shows a consistent increase in sales from March to July before a slight decline in August and September.</li>
<li>Asia: Exhibits a similar trend to Africa, with increasing sales until July followed by a slight decrease in August and September.</li>
<li>Canada: Sales follow a pattern similar to Africa and Asia, with a peak in July followed by a decline in August and September.</li>
<li>Europe: Shows a steady increase in sales from March to July, followed by a slight decrease in August and September.</li>
<li>Oceania: Shows the highest sales among all regions, with a peak in July followed by a decline in August and September.</li>
<li>South America: Sales follow a similar pattern to other regions, with a peak in July followed by a decline in August and September.</li>
<li>USA: Shows a consistent increase in sales from March to July before a slight decline in August and September.</li>
</ul></li>
<li><p><strong>Regional Variations</strong>:</p>
<ul>
<li>Oceania: consistently records the highest sales, indicating strong demand or market presence in that region.</li>
<li>Europe: Reports the lowest sales compared to other regions, suggesting potential opportunities for growth or market penetration strategies.</li>
</ul></li>
<li><p><strong>Seasonal Trends</strong>:</p>
<ul>
<li>The months of March to July generally witness higher sales across all regions, suggesting potential seasonal factors or marketing campaigns driving increased consumer spending during this period.</li>
<li>The decline in sales observed in August and September across most regions could be attributed to seasonal factors, economic conditions, or specific market dynamics.</li>
</ul></li>
<li><p><strong>Recommendations</strong>:</p>
<ul>
<li>Data Mart should analyze the factors contributing to the peak sales months to identify successful strategies and replicate them in other periods or regions.</li>
<li>Targeted marketing campaigns or promotions could be implemented during periods of lower sales to stimulate demand and boost revenue.</li>
<li>Understanding regional preferences and consumer behavior can help tailor marketing strategies and product offerings to maximize sales potential in each market.</li>
</ul></li>
</ol>
</section>
</section>
<section id="what-is-the-total-count-of-transactions-for-each-platform" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-total-count-of-transactions-for-each-platform">5. What is the total count of transactions for each platform?</h3>
<div class="sourceCode" id="cb7"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> platform,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(transactions) <span class="kw">as</span> total_transactions</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> platform</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> platform;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<thead>
<tr class="header">
<th>platform</th>
<th>total_transactions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Retail</td>
<td>1,081,934,227</td>
</tr>
<tr class="even">
<td>Shopify</td>
<td>5,925,169</td>
</tr>
</tbody>
</table>
<section id="total-transactions-by-platform" class="level4">
<h4 class="anchored" data-anchor-id="total-transactions-by-platform">Total Transactions by Platform</h4>
<ol type="1">
<li><p><strong>Insight</strong>:</p>
<ul>
<li>The majority of transactions occur through the Retail platform compared to the Shopify platform.</li>
</ul></li>
<li><p><strong>Observations</strong>:</p>
<ul>
<li>The higher transaction count on the Retail platform suggests a strong presence in physical retail locations or a larger customer base utilizing traditional retail channels.</li>
<li>The lower transaction count on the Shopify platform may indicate a smaller but growing segment of customers preferring online shopping experiences.</li>
</ul></li>
<li><p><strong>Opportunities</strong>:</p>
<ul>
<li>Data Mart could focus on enhancing its online platform to capture a larger share of the digital market and compete more effectively with traditional retail channels.</li>
<li>Leveraging data analytics and customer insights from both platforms can help optimize marketing strategies and product offerings to target specific customer segments more effectively.</li>
</ul></li>
</ol>
</section>
</section>
<section id="what-is-the-percentage-of-sales-for-retail-vs-shopify-for-each-month" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-percentage-of-sales-for-retail-vs-shopify-for-each-month">6. What is the percentage of sales for Retail vs Shopify for each month?</h3>
<div class="sourceCode" id="cb8"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> platform_sales <span class="kw">AS</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>(<span class="kw">SELECT</span> calendar_year, month_number,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> platform <span class="op">=</span> <span class="st">'Retail'</span> <span class="cf">THEN</span> sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> retail_sales,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> platform <span class="op">=</span> <span class="st">'Shopify'</span> <span class="cf">THEN</span> sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> shopify_sales,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> calendar_year, month_number</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> calendar_year, month_number)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> calendar_year, month_number,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (retail_sales<span class="op">/</span>total_sales), <span class="dv">2</span>) <span class="kw">AS</span> retail_sales_pct,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (shopify_sales<span class="op">/</span>total_sales), <span class="dv">2</span>) <span class="kw">AS</span> shopify_sales_pct</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> platform_sales;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<colgroup>
<col style="width: 21%">
<col style="width: 20%">
<col style="width: 27%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>calendar_year</th>
<th>month_number</th>
<th>retail_sales_pct</th>
<th>shopify_sales_pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2018</td>
<td>3</td>
<td>97.92</td>
<td>2.08</td>
</tr>
<tr class="even">
<td>2018</td>
<td>4</td>
<td>97.93</td>
<td>2.07</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>5</td>
<td>97.73</td>
<td>2.27</td>
</tr>
<tr class="even">
<td>2018</td>
<td>6</td>
<td>97.76</td>
<td>2.24</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>7</td>
<td>97.75</td>
<td>2.25</td>
</tr>
<tr class="even">
<td>2018</td>
<td>8</td>
<td>97.71</td>
<td>2.29</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>9</td>
<td>97.68</td>
<td>2.32</td>
</tr>
<tr class="even">
<td>2019</td>
<td>3</td>
<td>97.71</td>
<td>2.29</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>4</td>
<td>97.80</td>
<td>2.20</td>
</tr>
<tr class="even">
<td>2019</td>
<td>5</td>
<td>97.52</td>
<td>2.48</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>6</td>
<td>97.42</td>
<td>2.58</td>
</tr>
<tr class="even">
<td>2019</td>
<td>7</td>
<td>97.35</td>
<td>2.65</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>8</td>
<td>97.21</td>
<td>2.79</td>
</tr>
<tr class="even">
<td>2019</td>
<td>9</td>
<td>97.09</td>
<td>2.91</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>3</td>
<td>97.30</td>
<td>2.70</td>
</tr>
<tr class="even">
<td>2020</td>
<td>4</td>
<td>96.96</td>
<td>3.04</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>5</td>
<td>96.71</td>
<td>3.29</td>
</tr>
<tr class="even">
<td>2020</td>
<td>6</td>
<td>96.80</td>
<td>3.20</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>7</td>
<td>96.67</td>
<td>3.33</td>
</tr>
<tr class="even">
<td>2020</td>
<td>8</td>
<td>96.51</td>
<td>3.49</td>
</tr>
</tbody>
</table>
<section id="total-transactions-by-platform-1" class="level4">
<h4 class="anchored" data-anchor-id="total-transactions-by-platform-1">Total Transactions by Platform</h4>
<ol type="1">
<li><p><strong>Insight</strong>:</p>
<ul>
<li>The percentage of sales from the Retail platform consistently dominates over Shopify platform across monthsand years,indicatingthe continued siginificance of Physical stores. However, Shopify’s contributionto total sales has been steadily increasing overtime, suggesting an opportunity to grow online sales.</li>
</ul></li>
</ol>
</section>
</section>
<section id="what-is-the-percentage-of-sales-by-demographic-for-each-year-in-the-dataset" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-percentage-of-sales-by-demographic-for-each-year-in-the-dataset">7. What is the percentage of sales by demographic for each year in the dataset?</h3>
<div class="sourceCode" id="cb9"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> demographic_sales <span class="kw">AS</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>(<span class="kw">SELECT</span> calendar_year,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> demographic <span class="op">=</span> <span class="st">'Couples'</span> <span class="cf">THEN</span> sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> couples_sales,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> demographic <span class="op">=</span> <span class="st">'Families'</span> <span class="cf">THEN</span> sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> families_sales,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> demographic <span class="op">=</span> <span class="st">'unknown'</span> <span class="cf">THEN</span> sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> unknown_sales,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> calendar_year</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> calendar_year)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> calendar_year,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (couples_sales<span class="op">/</span>total_sales), <span class="dv">2</span>) <span class="kw">AS</span> couples_sales_pct,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (families_sales<span class="op">/</span>total_sales), <span class="dv">2</span>) <span class="kw">AS</span> families_sales_pct,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (unknown_sales<span class="op">/</span>total_sales), <span class="dv">2</span>) <span class="kw">AS</span> unknown_sales_pct</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> demographic_sales;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 25%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>calendar_year</th>
<th>couples_sales_pct</th>
<th>families_sales_pct</th>
<th>unknown_sales_pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2018</td>
<td>26.38</td>
<td>31.99</td>
<td>41.63</td>
</tr>
<tr class="even">
<td>2019</td>
<td>27.28</td>
<td>32.47</td>
<td>40.25</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>28.72</td>
<td>32.73</td>
<td>38.55</td>
</tr>
</tbody>
</table>
<section id="percentage-of-sales-by-demographic-for-each-year" class="level4">
<h4 class="anchored" data-anchor-id="percentage-of-sales-by-demographic-for-each-year">Percentage of Sales by Demographic for Each Year</h4>
<ol type="1">
<li><p><strong>Insight</strong>:</p>
<ul>
<li>Couples consistently contribute the least to total sales across all years, with families and unknown demographics making up the majority.</li>
</ul></li>
</ol>
</section>
</section>
<section id="which-age_band-and-demographic-values-contribute-the-most-to-retail-sales" class="level3">
<h3 class="anchored" data-anchor-id="which-age_band-and-demographic-values-contribute-the-most-to-retail-sales">8. Which age_band and demographic values contribute the most to Retail sales?</h3>
<div class="sourceCode" id="cb10"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> age_band, demographic,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> platform <span class="op">=</span> <span class="st">'Retail'</span> <span class="cf">THEN</span> sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>),<span class="dv">2</span>) <span class="kw">AS</span> retail_sales</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> retail_sales <span class="kw">DESC</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<thead>
<tr class="header">
<th>age_band</th>
<th>demographic</th>
<th>retail_sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>unknown</td>
<td>unknown</td>
<td>16067285533</td>
</tr>
<tr class="even">
<td>Retirees</td>
<td>Families</td>
<td>6634686916</td>
</tr>
<tr class="odd">
<td>Retirees</td>
<td>Couples</td>
<td>6370580014</td>
</tr>
<tr class="even">
<td>Middle Aged</td>
<td>Families</td>
<td>4354091554</td>
</tr>
<tr class="odd">
<td>Young Adults</td>
<td>Couples</td>
<td>2602922797</td>
</tr>
<tr class="even">
<td>Middle Aged</td>
<td>Couples</td>
<td>1854160330</td>
</tr>
<tr class="odd">
<td>Young Adults</td>
<td>Families</td>
<td>1770889293</td>
</tr>
</tbody>
</table>
<section id="retail-sales-contribution-by-age-band-and-demographic" class="level4">
<h4 class="anchored" data-anchor-id="retail-sales-contribution-by-age-band-and-demographic">Retail Sales Contribution by Age Band and Demographic</h4>
<ol type="1">
<li><p><strong>Insight</strong>:</p>
<ul>
<li>The demographic category “Unknown” contributes significantly more to retail sales compared to other age bands and demographics, indicating that a large portion of sales data lacks detailed demographic information.</li>
<li>Among known demographics, retirees, especially those in families, contribute significantly to retail sales, followed by middle-aged customers, primarily in families and couples.</li>
<li>Young adults, both in couples and families, contribute less compared to retirees and middle-aged individuals.</li>
</ul></li>
</ol>
</section>
</section>
<section id="can-we-use-the-avg_transaction-column-to-find-the-average-transaction-size-for-each-year-for-retail-vs-shopify-if-not---how-would-you-calculate-it-instead" class="level3">
<h3 class="anchored" data-anchor-id="can-we-use-the-avg_transaction-column-to-find-the-average-transaction-size-for-each-year-for-retail-vs-shopify-if-not---how-would-you-calculate-it-instead">9. Can we use the avg_transaction column to find the average transaction size for each year for Retail vs Shopify? If not - how would you calculate it instead?</h3>
<div class="sourceCode" id="cb11"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> calendar_year, platform,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ROUND</span>(<span class="fu">AVG</span>(avg_transaction), <span class="dv">2</span>) <span class="kw">AS</span> avg_transactions_1,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ROUND</span>(<span class="fu">SUM</span>(sales)<span class="op">/</span><span class="fu">SUM</span>(transactions), <span class="dv">2</span>) <span class="kw">AS</span> avg_transactions_2</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> calendar_year, platform</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> calendar_year, platform;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<thead>
<tr class="header">
<th>calendar_year</th>
<th>platform</th>
<th>avg_transactions_1</th>
<th>avg_transactions_2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2018</td>
<td>Retail</td>
<td>42.91</td>
<td>36.56</td>
</tr>
<tr class="even">
<td>2018</td>
<td>Shopify</td>
<td>188.28</td>
<td>192.48</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>Retail</td>
<td>41.97</td>
<td>36.83</td>
</tr>
<tr class="even">
<td>2019</td>
<td>Shopify</td>
<td>177.56</td>
<td>183.36</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>Retail</td>
<td>40.64</td>
<td>36.56</td>
</tr>
<tr class="even">
<td>2020</td>
<td>Shopify</td>
<td>174.87</td>
<td>179.03</td>
</tr>
</tbody>
</table>
<section id="average-transaction-size-comparison" class="level4">
<h4 class="anchored" data-anchor-id="average-transaction-size-comparison">Average Transaction Size Comparison</h4>
<ol type="1">
<li><p><strong>Insights</strong>:</p>
<ul>
<li>Avg_Transactions_1: Represents the average value of the avg_transaction column directly. This approach yields different results for each platform, reflecting the variability in average transaction sizes within each platform.</li>
<li>Avg_Transactions_2: Calculated by dividing the total sales by the total number of transactions. This method provides a more accurate reflection of the average transaction size, considering the actual sales amounts and transaction counts. It ensures consistency in calculation across platforms, making it a more reliable metric for comparison.</li>
</ul></li>
</ol>
</section>
</section>
<section id="before-after-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="before-after-analysis-1">3. Before &amp; After Analysis</h3>
<p>This technique is usually used when we inspect an important event and want to inspect the impact before and after a certain point in time.</p>
<p>Taking the <code>week_date</code> value of <code>2020-06-15</code> as the baseline week where the Data Mart sustainable packaging changes came into effect.</p>
<p>We would include all <code>week_date</code> values for <code>2020-06-15</code> as the start of the period <strong>after</strong> the change and the previous <code>week_date</code> values would be <strong>before</strong></p>
<p>Using this analysis approach - answer the following questions:</p>
</section>
<section id="what-is-the-total-sales-for-the-4-weeks-before-and-after-2020-06-15-what-is-the-growth-or-reduction-rate-in-actual-values-and-percentage-of-sales" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-total-sales-for-the-4-weeks-before-and-after-2020-06-15-what-is-the-growth-or-reduction-rate-in-actual-values-and-percentage-of-sales">1. What is the total sales for the 4 weeks before and after 2020-06-15? What is the growth or reduction rate in actual values and percentage of sales? */</h3>
<div class="sourceCode" id="cb12"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="kw">DISTINCT</span>(week_number) <span class="kw">AS</span> baseline_week_number <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> week_date <span class="op">=</span> <span class="st">'2020-06-15'</span> <span class="kw">AND</span> calendar_year <span class="op">=</span> <span class="st">'2020'</span>;</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> before_and_after_data <span class="kw">AS</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>(<span class="kw">SELECT</span> week_date,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        week_number,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>        <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">WHERE</span> (week_number <span class="kw">BETWEEN</span> <span class="dv">20</span> <span class="kw">AND</span> <span class="dv">27</span>) <span class="kw">AND</span> (calendar_year <span class="op">=</span> <span class="st">'2020'</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">GROUP</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="kw">ORDER</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>),</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>sales_calculation_table_before_and_after <span class="kw">AS</span> (</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>        <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="kw">IN</span> (<span class="dv">20</span>,<span class="dv">21</span>,<span class="dv">22</span>,<span class="dv">23</span>) <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_before_baseline_date_value,</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>        <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="kw">IN</span> (<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">27</span>) <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_after_baseline_date_value</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>        <span class="kw">FROM</span> before_and_after_data</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>        sales_before_baseline_date_value, sales_after_baseline_date_value,</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>        (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value) <span class="kw">AS</span> difference,</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value)<span class="op">/</span>sales_before_baseline_date_value,<span class="dv">2</span>) <span class="kw">AS</span> pct</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> sales_calculation_table_before_and_after;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<p>The Baseline week_number is <code>24</code>.</p>
<table class="table">
<colgroup>
<col style="width: 41%">
<col style="width: 39%">
<col style="width: 12%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>sales_before_baseline_date_value</th>
<th>sales_after_baseline_date_value</th>
<th>difference</th>
<th>pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2345878357</td>
<td>2318994169</td>
<td>-26884188</td>
<td>-1.15</td>
</tr>
</tbody>
</table>
<section id="total-sales-comparison-4-weeks-before-and-after-2020-06-15" class="level4">
<h4 class="anchored" data-anchor-id="total-sales-comparison-4-weeks-before-and-after-2020-06-15">Total Sales Comparison: 4 Weeks Before and After 2020-06-15</h4>
<ol type="1">
<li><p><strong>Insights</strong>:</p>
<ul>
<li>The total sales decreased by approximately $26.88 million after the baseline date compared to the four weeks before.</li>
<li>This corresponds to a reduction of approximately 1.15% in sales during the four weeks after the baseline date compared to the four weeks before.</li>
</ul></li>
</ol>
</section>
</section>
<section id="what-about-the-entire-12-weeks-before-and-after" class="level3">
<h3 class="anchored" data-anchor-id="what-about-the-entire-12-weeks-before-and-after">2. What about the entire 12 weeks before and after?</h3>
<div class="sourceCode" id="cb13"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> before_and_after_data <span class="kw">AS</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>(<span class="kw">SELECT</span> week_date, week_number, <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> calendar_year <span class="op">=</span> <span class="st">'2020'</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> week_date, week_number</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> week_date, week_number</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>sales_calculation_table_before_and_after <span class="kw">AS</span> (</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>        <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&lt;</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_before_baseline_date_value,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>        <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&gt;=</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_after_baseline_date_value</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> before_and_after_data)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    sales_before_baseline_date_value, sales_after_baseline_date_value,</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value) <span class="kw">AS</span> difference,</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value)<span class="op">/</span>sales_before_baseline_date_value,<span class="dv">2</span>) <span class="kw">AS</span> pct</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> sales_calculation_table_before_and_after;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<colgroup>
<col style="width: 41%">
<col style="width: 39%">
<col style="width: 12%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>sales_before_baseline_date_value</th>
<th>sales_after_baseline_date_value</th>
<th>difference</th>
<th>pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7126273147</td>
<td>6973947753</td>
<td>-152325394</td>
<td>-2.14</td>
</tr>
</tbody>
</table>
<section id="total-sales-comparison-12-weeks-before-and-after-2020-06-15" class="level4">
<h4 class="anchored" data-anchor-id="total-sales-comparison-12-weeks-before-and-after-2020-06-15">Total Sales Comparison: 12 Weeks Before and After 2020-06-15</h4>
<ol type="1">
<li><p><strong>Insights</strong>:</p>
<ul>
<li>The total sales decreased by approximately $152.33 million over the entire 12 weeks after the baseline date compared to the 12 weeks before.</li>
<li>This corresponds to a reduction of approximately 2.14% in sales during the 12 weeks after the baseline date compared to the 12 weeks before.</li>
</ul></li>
</ol>
</section>
</section>
<section id="how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-4-weeks-period" class="level3">
<h3 class="anchored" data-anchor-id="how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-4-weeks-period">3. How do the sale metrics for these 2 periods before and after compare with the previous years in 2018 and 2019 for 4 weeks period?</h3>
<p>Part 3.1: How do the sale metrics for these 2 periods before and after compare with the previous years in 2018 and 2019 for 4 weeks period?</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> before_and_after_data <span class="kw">AS</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>(<span class="kw">SELECT</span> calendar_year, week_number,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> (week_number <span class="kw">BETWEEN</span> <span class="dv">20</span> <span class="kw">AND</span> <span class="dv">27</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> calendar_year, week_number</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> calendar_year, week_number</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>sales_calculation_table_before_and_after <span class="kw">AS</span> (</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> calendar_year,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>        <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="kw">IN</span> (<span class="dv">20</span>,<span class="dv">21</span>,<span class="dv">22</span>,<span class="dv">23</span>) <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_before_baseline_date_value,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>        <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="kw">IN</span> (<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">27</span>) <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_after_baseline_date_value</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> before_and_after_data</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">GROUP</span> <span class="kw">BY</span> calendar_year</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> calendar_year,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    sales_before_baseline_date_value, sales_after_baseline_date_value,</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value) <span class="kw">AS</span> difference,</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>    <span class="op">/</span>sales_before_baseline_date_value,<span class="dv">2</span>) <span class="kw">AS</span> pct</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> sales_calculation_table_before_and_after;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 11%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>calendar_year</th>
<th>sales_before_baseline_date_value</th>
<th>sales_after_baseline_date_value</th>
<th>difference</th>
<th>pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2018</td>
<td>2125140809</td>
<td>2129242914</td>
<td>4102105</td>
<td>0.19</td>
</tr>
<tr class="even">
<td>2019</td>
<td>2249989796</td>
<td>2252326390</td>
<td>2336594</td>
<td>0.10</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>2345878357</td>
<td>2318994169</td>
<td>-26884188</td>
<td>-1.15</td>
</tr>
</tbody>
</table>
<section id="sale-metrics-comparison-4-weeks-before-and-after-2020-06-15-across-years-2018-2019-and-2020" class="level4">
<h4 class="anchored" data-anchor-id="sale-metrics-comparison-4-weeks-before-and-after-2020-06-15-across-years-2018-2019-and-2020">Sale Metrics Comparison: 4 Weeks Before and After 2020-06-15 Across Years (2018, 2019, and 2020)</h4>
<ol type="1">
<li><p><strong>Overall Trend</strong>:</p>
<ul>
<li>While there were slight increases in sales in the 4 weeks after compared to before for both 2018 and 2019, there was a noticeable decrease in sales in 2020, indicating a negative impact on sales during this period compared to previous years.</li>
</ul></li>
</ol>
</section>
</section>
<section id="how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-4-weeks-period-1" class="level3">
<h3 class="anchored" data-anchor-id="how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-4-weeks-period-1">3. How do the sale metrics for these 2 periods before and after compare with the previous years in 2018 and 2019 for 4 weeks period?</h3>
<p>Part 3.1: How do the sale metrics for these 2 periods before and after compare with the previous years in 2018 and 2019 for 4 weeks period?</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> before_and_after_data <span class="kw">AS</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>(<span class="kw">SELECT</span> calendar_year, week_number,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> (week_number <span class="kw">BETWEEN</span> <span class="dv">20</span> <span class="kw">AND</span> <span class="dv">27</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> calendar_year, week_number</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> calendar_year, week_number</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>sales_calculation_table_before_and_after <span class="kw">AS</span> (</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> calendar_year,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>        <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="kw">IN</span> (<span class="dv">20</span>,<span class="dv">21</span>,<span class="dv">22</span>,<span class="dv">23</span>) <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_before_baseline_date_value,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>        <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="kw">IN</span> (<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">27</span>) <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_after_baseline_date_value</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> before_and_after_data</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">GROUP</span> <span class="kw">BY</span> calendar_year</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> calendar_year,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    sales_before_baseline_date_value, sales_after_baseline_date_value,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value) <span class="kw">AS</span> difference,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>    <span class="op">/</span>sales_before_baseline_date_value,<span class="dv">2</span>) <span class="kw">AS</span> pct</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> sales_calculation_table_before_and_after;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 11%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>calendar_year</th>
<th>sales_before_baseline_date_value</th>
<th>sales_after_baseline_date_value</th>
<th>difference</th>
<th>pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2018</td>
<td>2125140809</td>
<td>2129242914</td>
<td>4102105</td>
<td>0.19</td>
</tr>
<tr class="even">
<td>2019</td>
<td>2249989796</td>
<td>2252326390</td>
<td>2336594</td>
<td>0.10</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>2345878357</td>
<td>2318994169</td>
<td>-26884188</td>
<td>-1.15</td>
</tr>
</tbody>
</table>
<section id="sale-metrics-comparison-4-weeks-before-and-after-2020-06-15-across-years-2018-2019-and-2020-1" class="level4">
<h4 class="anchored" data-anchor-id="sale-metrics-comparison-4-weeks-before-and-after-2020-06-15-across-years-2018-2019-and-2020-1">Sale Metrics Comparison: 4 Weeks Before and After 2020-06-15 Across Years (2018, 2019, and 2020)</h4>
<ol type="1">
<li><p><strong>Overall Trend</strong>:</p>
<ul>
<li>While there were slight increases in sales in the 4 weeks after compared to before for both 2018 and 2019, there was a noticeable decrease in sales in 2020, indicating a negative impact on sales during this period compared to previous years.</li>
</ul></li>
</ol>
</section>
</section>
<section id="part-3.2-how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-12-weeks-period" class="level3">
<h3 class="anchored" data-anchor-id="part-3.2-how-do-the-sale-metrics-for-these-2-periods-before-and-after-compare-with-the-previous-years-in-2018-and-2019-for-12-weeks-period">Part 3.2: How do the sale metrics for these 2 periods before and after compare with the previous years in 2018 and 2019 for 12 weeks period?</h3>
<div class="sourceCode" id="cb16"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> before_and_after_data <span class="kw">AS</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    (<span class="kw">SELECT</span> calendar_year, week_number,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>        <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">GROUP</span> <span class="kw">BY</span> calendar_year, week_number</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">ORDER</span> <span class="kw">BY</span> calendar_year, week_number</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    ), sales_calculation_table_before_and_after <span class="kw">AS</span> (</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>        <span class="kw">SELECT</span> calendar_year,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&lt;</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_before_baseline_date_value,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&gt;=</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_after_baseline_date_value</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>        <span class="kw">FROM</span> before_and_after_data</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>        <span class="kw">GROUP</span> <span class="kw">BY</span> calendar_year</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> calendar_year,</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>        sales_before_baseline_date_value, sales_after_baseline_date_value,</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>        (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value) <span class="kw">AS</span> difference,</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value)<span class="op">/</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>            sales_before_baseline_date_value,<span class="dv">2</span>) <span class="kw">AS</span> pct</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> sales_calculation_table_before_and_after;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 11%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>calendar_year</th>
<th>sales_before_baseline_date_value</th>
<th>sales_after_baseline_date_value</th>
<th>difference</th>
<th>pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2018</td>
<td>6396562317</td>
<td>6500818510</td>
<td>104256193</td>
<td>1.63</td>
</tr>
<tr class="even">
<td>2019</td>
<td>6883386397</td>
<td>6862646103</td>
<td>-20740294</td>
<td>-0.30</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>7126273147</td>
<td>6973947753</td>
<td>-152325394</td>
<td>-2.14</td>
</tr>
</tbody>
</table>
<section id="sale-metrics-comparison-12-weeks-before-and-after-2020-06-15-across-years-2018-2019-and-2020" class="level4">
<h4 class="anchored" data-anchor-id="sale-metrics-comparison-12-weeks-before-and-after-2020-06-15-across-years-2018-2019-and-2020">Sale Metrics Comparison: 12 Weeks Before and After 2020-06-15 Across Years (2018, 2019, and 2020)</h4>
<ol type="1">
<li><p><strong>Overall Trend</strong>:</p>
<ul>
<li>While there was a significant increase in sales in 2018 and a slight decrease in 2019, 2020 saw a notable decrease in sales during this period compared to previous years. This suggests a significant negative impact on sales in 2020 compared to earlier years.</li>
</ul></li>
</ol>
</section>
</section>
<section id="bonus-question-1" class="level3">
<h3 class="anchored" data-anchor-id="bonus-question-1">4. Bonus Question</h3>
<p>Which areas of the business have the highest negative impact in sales metrics performance in 2020 for the 12 week before and after period?</p>
<ul>
<li><code>region</code></li>
<li><code>platform</code></li>
<li><code>age_band</code></li>
<li><code>demographic</code></li>
<li><code>customer_type</code></li>
</ul>
<p>Do you have any further recommendations for Danny’s team at Data Mart or any interesting insights based off this analysis?</p>
</section>
<section id="which-areas-of-the-business-have-the-highest-negative-impact-in-sales-metrics-performance-in-2020-for-the-12-week-before-and-after-period" class="level3">
<h3 class="anchored" data-anchor-id="which-areas-of-the-business-have-the-highest-negative-impact-in-sales-metrics-performance-in-2020-for-the-12-week-before-and-after-period">Which areas of the business have the highest negative impact in sales metrics performance in 2020 for the 12 week before and after period?</h3>
<pre><code>-- region
-- platform
-- age_band
-- demographic
-- customer_type</code></pre>
<p>Do you have any further recommendations for Danny’s team at Data Mart or any interesting insights based off this analysis?</p>
<p>Answer:</p>
<p>Sales metric performance across region.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> before_and_after_data <span class="kw">AS</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>       (<span class="kw">SELECT</span> region,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>            week_number,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>            <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>        <span class="kw">GROUP</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>        <span class="kw">ORDER</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>       ),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>       sales_calculation_table_before_and_after <span class="kw">AS</span> (</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>       <span class="kw">SELECT</span> region,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&lt;</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_before_baseline_date_value,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&gt;=</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_after_baseline_date_value</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>            <span class="kw">FROM</span> before_and_after_data</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>            <span class="kw">GROUP</span> <span class="kw">BY</span> region</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>        <span class="kw">SELECT</span> region,</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>            sales_before_baseline_date_value, sales_after_baseline_date_value,</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>            (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value) <span class="kw">AS</span> difference,</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value)<span class="op">/</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>                sales_before_baseline_date_value,<span class="dv">2</span>) <span class="kw">AS</span> pct</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>        <span class="kw">FROM</span> sales_calculation_table_before_and_after;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 12%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Region</th>
<th>Sales Before Baseline Date</th>
<th>Sales After Baseline Date</th>
<th>Difference</th>
<th>Percent Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AFRICA</td>
<td>4942976910</td>
<td>4997516159</td>
<td>54539249</td>
<td>1.10</td>
</tr>
<tr class="even">
<td>ASIA</td>
<td>4613242689</td>
<td>4551927271</td>
<td>-61315418</td>
<td>-1.33</td>
</tr>
<tr class="odd">
<td>CANADA</td>
<td>1244662705</td>
<td>1234025206</td>
<td>-10637499</td>
<td>-0.85</td>
</tr>
<tr class="even">
<td>EUROPE</td>
<td>328141414</td>
<td>344420043</td>
<td>16278629</td>
<td>4.96</td>
</tr>
<tr class="odd">
<td>OCEANIA</td>
<td>6698586333</td>
<td>6640244793</td>
<td>-58341540</td>
<td>-0.87</td>
</tr>
<tr class="even">
<td>SOUTH AMERICA</td>
<td>611056923</td>
<td>608981392</td>
<td>-2075531</td>
<td>-0.34</td>
</tr>
<tr class="odd">
<td>USA</td>
<td>1967554887</td>
<td>1960297502</td>
<td>-7257385</td>
<td>-0.37</td>
</tr>
</tbody>
</table>
<p>Sales metric performance across platform.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> before_and_after_data <span class="kw">AS</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>       (<span class="kw">SELECT</span> platform,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>            week_number,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>            <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>        <span class="kw">GROUP</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>        <span class="kw">ORDER</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>       ),</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>       sales_calculation_table_before_and_after <span class="kw">AS</span> (</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>       <span class="kw">SELECT</span> platform,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&lt;</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_before_baseline_date_value,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&gt;=</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_after_baseline_date_value</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>            <span class="kw">FROM</span> before_and_after_data</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>            <span class="kw">GROUP</span> <span class="kw">BY</span> platform</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>        <span class="kw">SELECT</span> platform,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>            sales_before_baseline_date_value, sales_after_baseline_date_value,</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>            (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value) <span class="kw">AS</span> difference,</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value)<span class="op">/</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>                sales_before_baseline_date_value,<span class="dv">2</span>) <span class="kw">AS</span> pct</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>        <span class="kw">FROM</span> sales_calculation_table_before_and_after;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 30%">
<col style="width: 29%">
<col style="width: 13%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Platform</th>
<th>Sales Before Baseline Date</th>
<th>Sales After Baseline Date</th>
<th>Difference</th>
<th>Percent Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Retail</td>
<td>19886040272</td>
<td>19768576165</td>
<td>-117464107</td>
<td>-0.59</td>
</tr>
<tr class="even">
<td>Shopify</td>
<td>520181589</td>
<td>568836201</td>
<td>48654612</td>
<td>9.35</td>
</tr>
</tbody>
</table>
<p>Sales metric performance across age_band.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> before_and_after_data <span class="kw">AS</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>       (<span class="kw">SELECT</span> age_band,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>            week_number,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>            <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>        <span class="kw">GROUP</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>        <span class="kw">ORDER</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>       ),</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>       sales_calculation_table_before_and_after <span class="kw">AS</span> (</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>       <span class="kw">SELECT</span> age_band,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&lt;</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_before_baseline_date_value,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&gt;=</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_after_baseline_date_value</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>            <span class="kw">FROM</span> before_and_after_data</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>            <span class="kw">GROUP</span> <span class="kw">BY</span> age_band</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>        <span class="kw">SELECT</span> age_band,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>            sales_before_baseline_date_value, sales_after_baseline_date_value,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>            (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value) <span class="kw">AS</span> difference,</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value)<span class="op">/</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>                sales_before_baseline_date_value,<span class="dv">2</span>) <span class="kw">AS</span> pct</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>        <span class="kw">FROM</span> sales_calculation_table_before_and_after;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 13%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Age Band</th>
<th>Sales Before Baseline Date</th>
<th>Sales After Baseline Date</th>
<th>Difference</th>
<th>Percent Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Middle Aged</td>
<td>3276892347</td>
<td>3269748622</td>
<td>-7143725</td>
<td>-0.22</td>
</tr>
<tr class="even">
<td>Retirees</td>
<td>6646865322</td>
<td>6634706880</td>
<td>-12158442</td>
<td>-0.18</td>
</tr>
<tr class="odd">
<td>Unknown</td>
<td>8191628826</td>
<td>8146983408</td>
<td>-44645418</td>
<td>-0.55</td>
</tr>
<tr class="even">
<td>Young Adults</td>
<td>2290835366</td>
<td>2285973456</td>
<td>-4861910</td>
<td>-0.21</td>
</tr>
</tbody>
</table>
<p>Sales metric performance across demographic.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> before_and_after_data <span class="kw">AS</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>       (<span class="kw">SELECT</span> demographic,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>            week_number,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>            <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>        <span class="kw">GROUP</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>        <span class="kw">ORDER</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>       ),</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>       sales_calculation_table_before_and_after <span class="kw">AS</span> (</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>       <span class="kw">SELECT</span> demographic,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&lt;</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_before_baseline_date_value,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&gt;=</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_after_baseline_date_value</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>            <span class="kw">FROM</span> before_and_after_data</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>            <span class="kw">GROUP</span> <span class="kw">BY</span> demographic</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>        <span class="kw">SELECT</span> demographic,</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>            sales_before_baseline_date_value, sales_after_baseline_date_value,</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>            (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value) <span class="kw">AS</span> difference,</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value)<span class="op">/</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>                sales_before_baseline_date_value,<span class="dv">2</span>) <span class="kw">AS</span> pct</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>        <span class="kw">FROM</span> sales_calculation_table_before_and_after;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 28%">
<col style="width: 27%">
<col style="width: 13%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Demographic</th>
<th>Sales Before Baseline Date</th>
<th>Sales After Baseline Date</th>
<th>Difference</th>
<th>Percent Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Couples</td>
<td>5608866131</td>
<td>5592341420</td>
<td>-16524711</td>
<td>-0.29</td>
</tr>
<tr class="even">
<td>Families</td>
<td>6605726904</td>
<td>6598087538</td>
<td>-7639366</td>
<td>-0.12</td>
</tr>
<tr class="odd">
<td>Unknown</td>
<td>8191628826</td>
<td>8146983408</td>
<td>-44645418</td>
<td>-0.55</td>
</tr>
</tbody>
</table>
<p>Sales metric performance across customer_type.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> before_and_after_data <span class="kw">AS</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>       (<span class="kw">SELECT</span> customer_type,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>            week_number,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(sales) <span class="kw">AS</span> total_sales</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>            <span class="kw">FROM</span> clean_weekly_sales</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>        <span class="kw">GROUP</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>        <span class="kw">ORDER</span> <span class="kw">BY</span> <span class="dv">1</span>,<span class="dv">2</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>       ),</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>       sales_calculation_table_before_and_after <span class="kw">AS</span> (</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>       <span class="kw">SELECT</span> customer_type,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&lt;</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_before_baseline_date_value,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">SUM</span>(<span class="cf">CASE</span> <span class="cf">WHEN</span> week_number <span class="op">&gt;=</span> <span class="dv">24</span> <span class="cf">THEN</span> total_sales <span class="cf">ELSE</span> <span class="dv">0</span> <span class="cf">END</span>) <span class="kw">AS</span> sales_after_baseline_date_value</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>            <span class="kw">FROM</span> before_and_after_data</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>            <span class="kw">GROUP</span> <span class="kw">BY</span> customer_type</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>        <span class="kw">SELECT</span> customer_type,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>            sales_before_baseline_date_value, sales_after_baseline_date_value,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>            (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value) <span class="kw">AS</span> difference,</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ROUND</span>(<span class="fl">100.0</span> <span class="op">*</span> (sales_after_baseline_date_value <span class="op">-</span> sales_before_baseline_date_value)<span class="op">/</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>                sales_before_baseline_date_value,<span class="dv">2</span>) <span class="kw">AS</span> pct</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>        <span class="kw">FROM</span> sales_calculation_table_before_and_after;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 28%">
<col style="width: 27%">
<col style="width: 13%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Customer Type</th>
<th>Sales Before Baseline Date</th>
<th>Sales After Baseline Date</th>
<th>Difference</th>
<th>Percent Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Existing</td>
<td>10168877642</td>
<td>10117367239</td>
<td>-51510403</td>
<td>-0.51</td>
</tr>
<tr class="even">
<td>Guest</td>
<td>7630353739</td>
<td>7595150744</td>
<td>-35202995</td>
<td>-0.46</td>
</tr>
<tr class="odd">
<td>New</td>
<td>2606990480</td>
<td>2624894383</td>
<td>17903903</td>
<td>0.69</td>
</tr>
</tbody>
</table>
<section id="sales-metric-performance-analysis-across-different-business-areas" class="level4">
<h4 class="anchored" data-anchor-id="sales-metric-performance-analysis-across-different-business-areas">Sales Metric Performance Analysis Across Different Business Areas</h4>
<ol type="1">
<li><p><strong>Sales Metric Performance Across Regions</strong>:</p>
<ul>
<li>Africa: Experienced a slight increase in sales (1.10%) after the baseline date.</li>
<li>Asia: Witnessed a decrease in sales (-1.33%) after the baseline date, indicating a negative impact.</li>
<li>Canada: Saw a minor decrease in sales (-0.85%) after the baseline date.</li>
<li>Europe: Showed a significant increase in sales (4.96%) after the baseline date, indicating positive performance.</li>
<li>Oceania: Experienced a decrease in sales (-0.87%) after the baseline date.</li>
<li>South America: Saw a slight decrease in sales (-0.34%) after the baseline date.</li>
<li>USA: Witnessed a decrease in sales (-0.37%) after the baseline date.</li>
</ul></li>
<li><p><strong>Sales Metric Performance Across Platforms</strong>:</p>
<ul>
<li>Retail: Experienced a decrease in sales (-0.59%) after the baseline date.</li>
<li>Shopify: Witnessed a significant increase in sales (9.35%) after the baseline date, indicating positive performance.</li>
</ul></li>
<li><p><strong>Sales Metric Performance Across Age Bands</strong>:</p>
<ul>
<li>Middle Aged: Experienced a minor decrease in sales (-0.22%) after the baseline date.</li>
<li>Retirees: Saw a slight decrease in sales (-0.18%) after the baseline date.</li>
<li>Unknown: Witnessed a notable decrease in sales (-0.55%) after the baseline date.</li>
<li>Young Adults: Experienced a minor decrease in sales (-0.21%) after the baseline date.</li>
</ul></li>
<li><p><strong>Sales Metric Performance Across Demographics</strong>:</p>
<ul>
<li>Couples: Experienced a slight decrease in sales (-0.29%) after the baseline date.</li>
<li>Families: Saw a minor decrease in sales (-0.12%) after the baseline date.</li>
<li>Unknown: Witnessed a notable decrease in sales (-0.55%) after the baseline date.</li>
</ul></li>
<li><p><strong>Sales Metric Performance Across Customer Types</strong>:</p>
<ul>
<li>Existing Customers: Experienced a decrease in sales (-0.51%) after the baseline date.</li>
<li>Guest Customers: Witnessed a decrease in sales (-0.46%) after the baseline date.</li>
<li>New Customers: Saw an increase in sales (0.69%) after the baseline date, indicating positive performance.</li>
</ul></li>
</ol>
</section>
<section id="conclusion-and-recommendations" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-and-recommendations">Conclusion and Recommendations:</h4>
<pre><code>- Overall Sales Performance: The analysis reveals mixed performance across different regions, platforms, age bands, demographics, and customer types.
- Positive Trends: Europe and Shopify platform showed significant increases in sales, suggesting areas of potential growth.
- Negative Trends: Asia, Oceania, and certain demographic segments experienced decreases in sales, requiring further investigation into underlying factors.

- Recommendations: Danny’s team should focus on leveraging positive trends, such as expanding operations in regions with growing sales and optimizing sales strategies for specific customer segments. Additionally, they should address issues contributing to sales declines, such as exploring new marketing strategies or improving product offerings. Regular monitoring and analysis of sales metrics across different business areas will be crucial for identifying opportunities and addressing challenges in the future.</code></pre>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>